### ISSUE TITLE
How to Log Observations?

### ISSUE THREAD

**Issue by orsenthil** [Stellarium/stellarium-web#9]
There is no green Plus button, when an object is selected in stellarium web.
How do we correctly log an observation? 

Thank you!

**Comment by xalioth** [comment]
Hi Senthil,

are you logged in? You need to create an account to log observations. To do
so, click in the upper right corner on the "Observe" button

Fabien

**Comment by orsenthil** [comment]
Hi Fabien, I see it now, For some reason when I tried the first time, I did not find the button (even after logging in). 

Thank you!
